# Generated by Django 4.2.6 on 2023-10-27 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_order_status_status_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.status'),
        ),
    ]
